#fourth_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  swerve_steering_controller:
    type: "swerve_controller/SwerveController"
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.667  # m/s
        min_velocity           : -1.667 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.14  # rad/s
        min_velocity           : -3.14
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0
    # Joints
    lf_wheel: "wheel_4"
    rf_wheel: "wheel_3"
    lh_wheel: "wheel_1"
    rh_wheel: "wheel_2"
    lf_steering: "steer4"
    rf_steering: "steer_3"
    lh_steering: "steer1"
    rh_steering: "steer2"

    # Range of motion of steering motors
    min_steering_angle: -1.58
    max_steering_angle: 1.58

    # Other
    publish_rate: 50
    enable_odom_tf: true
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 5
    base_frame_id: "base_link"
    enable_odom_tf: false
    # Geometry (Do not provide the following if you want it to be parsed in the URDF)
    # track: 0.8
    # wheel_steering_y_offset: 0
    # wheel_radius: 0.15
    # wheel_base: 1.2
    gazebo_ros_control:
        pid_gains:
            leg_lf_joint: {p: 50.0, i: 0.5, d: 5}
            leg_rf_joint: {p: 50.0, i: 0.5, d: 5}
            leg_lh_joint: {p: 50.0, i: 0.5, d: 5}
            leg_rh_joint: {p: 50.0, i: 0.5, d: 5}
            wheel_lf_joint: {p: 50.0, i: 2.0, d: 0.001}
            wheel_rf_joint: {p: 50.0, i: 2.0, d: 0.001}
            wheel_lh_joint: {p: 50.0, i: 2.0, d: 0.001}
            wheel_rh_joint: {p: 50.0, i: 2.0, d: 0.001}
# Low-Level Controllers -------------------------------------
  
  mars_rover:
    type        : "four_wheel_steering_controller/FourWheelSteeringController"
    front_wheel: ['wheel_4', 'wheel_3']
    rear_wheel: ['wheel_1', 'wheel_2']
    front_steering: ['steer4', 'steer_3']
    rear_steering: ['steer1', 'steer2']
    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    # cmd_vel_timeout: 25.0 # not tested here

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.60
    wheel_radius : 0.11
    # wheel_steering_y_offset : 0.03

    # # Wheel separation and radius multipliers
    # wheel_separation_multiplier: 1.0
    # wheel_radius_multiplier    : 1.0

    # # Velocity commands timeout [s], default 0.5
    # cmd_vel_timeout: 1.0
    
    # Base frame_id
    base_frame_id: base_link #default: base_link
    enable_odom_tf: false
    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.667  # m/s
        min_velocity           : -1.667 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.14  # rad/s
        min_velocity           : -3.14
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0

    /gazebo_ros_control:
      pid_gains:
        steer1:
          p: 50
          i: 1
          d: 0.01
        steer2:
          p: 50
          i: 1
          d: 0.01
        steer_3:
          p: 50
          i: 1
          d: 0.01
        steer4:
          p: 50
          i: 1
          d: 0.01
        wheel_1: #front_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        wheel_2: #front_right_wheel
          p: 10.0
          i: 1
          d: 0.0
        wheel_3: #rear_left_wheel
          p: 10.0
          i: 1
          d: 0.0
        wheel_4: #rear_right_wheel
          p: 10.0
          i: 1
          d: 0.0
